repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: crystal-format
        name: Format crystal files
        entry: crystal tool format compiler/
        language: system
        types: [crystal]

      - id: crystal-spec
        name: Run crystal spec
        entry: cd compiler && crystal spec --color --verbose
        language: system
        types: [crystal, bash]
