default_install_hook_types: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: crystal-format
        name: Format crystal files
        entry: crystal tool format compiler/
        language: system
        types: [crystal]

      - id: biome-format
        name: Format JS and TS files with Biome
        entry: biome format **/*.ts
        language: system
        types: [javascript, ts]

      - id: crystal-spec
        name: Run crystal spec
        entry: bash -c 'cd compiler && crystal spec --color --verbose'
        language: system
        types: [crystal]
        stages: [pre-push]
        pass_filenames: false
