repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: format-crystal-files
        name: Format crystal files
        files: r'*.cr'
        entry: .hooks/format-crystal-files.sh
        language: script
        pass_filenames: false
