// Do not edit this file!
// The tests are auto generated from [FILE_NAME]

import { Ananse } from "ananse";

const ussd = new Ananse().configure({
	gateway: 'wigal',
	session: 'memory',
});

import { BaseMenu, MenuRouter } from 'ananse';
  export class MenuHelloe7be5314 extends BaseMenu {
  isStart(): Promise<boolean> | boolean {
    return true;
  }async message() {
let var_604188ed = '';
var_604188ed = "Hello World!";
return var_604188ed;}
async nextMenu() {
return undefined; }
}
MenuRouter.add(MenuHelloe7be5314, 'hello');


const port = process.argv[2];
if (port == null) {
	throw new Error(
		"Port is required. Please provide a port number as argument to the script",
	);
}
ussd.listen(parseInt(port), "localhost", () => {
	console.log(`Server listening on port ${port}`);
});
