// Do not edit this file!
// The tests are auto generated from [FILE_NAME]

import { Ananse } from "ananse";

const ussd = new Ananse().configure({
	gateway: 'wigal',
	session: 'memory',
});

import { BaseMenu, MenuRouter, Request, Response, MenuAction } from 'ananse';
  export class MenuHellofe136594 extends BaseMenu {
  isStart(): Promise<boolean> | boolean {
    return true;
  }async message() {
let var_06a3a09d = '';
var_06a3a09d = "Hello World!";
return var_06a3a09d;}
async nextMenu() {
return undefined; }
}
MenuRouter.add(MenuHellofe136594, 'hello');


const port = process.argv[2];
if (port == null) {
	throw new Error(
		"Port is required. Please provide a port number as argument to the script",
	);
}
ussd.listen(parseInt(port), "localhost", () => {
	console.log(`Server listening on port ${port}`);
});
